import Head from "next/head";
import { Box, Typography } from "@mui/material";
import OrganizationSetup from "@/section/organizationSetup";
import ChatbotIntegration from "@/section/chatbotIntegration";
import { useState } from "react";
import RegistrationSection from "@/section/registrationForm";

export default function Home() {
  const [step, setStep] = useState(0);

  const nextStep = () => setStep((prevStep) => prevStep + 1);

  const prevStep = () => setStep((prevStep) => prevStep - 1);

  return (
    <>
      <Head>
        <title>Chatbot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{
        background: "#12372A", paddingTop: 8,
        minHeight: "100vh",
      }}>
        <Typography textAlign="center" sx={{ color: "#FCFCFC", fontSize: { md: "64px", xs: "45px" }, fontWeight: 800 }}>
          ChatBot
        </Typography>
        {step === 0 && <RegistrationSection onNext={nextStep} />}
        {step === 1 && <OrganizationSetup onNext={nextStep} onBack={prevStep} />}
        {step === 2 && <ChatbotIntegration onNext={nextStep} onBack={prevStep} />}
      </Box>
    </>
  );
}
